# Generated by Django 3.2.16 on 2023-03-24 05:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeTotalExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('Advertising', 'Advertising'), ('Bank Fees', 'Bank Fees'), ('Car', 'Car'), ('Cell Phone', 'Cell Phone'), ('Client Expense', 'Client Expense'), ('Computer', 'Computer'), ('Donation', 'Donation'), ('Insurance', 'Insurance'), ('Legal Fees', 'Legal Fees'), ('Office Expense', 'Office Expense'), ('Rent', 'Rent'), ('Recruitment & Training', 'Recruitment & Training'), ('Subscriptions', 'Subscriptions'), ('Tax Preparation Files', 'Tax Preparation Files'), ('Travel', 'Travel'), ('Utilities', 'Utilities'), ('Other', 'Other')], max_length=30)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('expense', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeMonthlyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('expense', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ContractorMonthlyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('expense', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.contractor')),
            ],
        ),
        migrations.CreateModel(
            name='ContractorMonthlyExpenseReport',
            fields=[
            ],
            options={
                'verbose_name': 'Contractors',
                'verbose_name_plural': 'Contractors',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('reports.contractormonthlyexpense',),
        ),
        migrations.CreateModel(
            name='EmployeeMonthlyExpenseReport',
            fields=[
            ],
            options={
                'verbose_name': 'Employees',
                'verbose_name_plural': 'Employees',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('reports.employeemonthlyexpense',),
        ),
        migrations.CreateModel(
            name='TypeTotalExpenseReport',
            fields=[
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('reports.typetotalexpense',),
        ),
    ]
