# Generated by Django 3.2.16 on 2023-10-11 15:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceMonthlyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyBudgetGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyBudgetTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PipelineMonthlyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TypeTotalExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('expense', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.expensetype')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeMonthlyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('expense', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ContractorMonthlyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('expense', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.contractor')),
            ],
        ),
        migrations.CreateModel(
            name='ContractorMonthlyExpenseReport',
            fields=[
            ],
            options={
                'verbose_name': 'Contractors',
                'verbose_name_plural': 'Contractors',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('reports.contractormonthlyexpense',),
        ),
        migrations.CreateModel(
            name='EmployeeMonthlyExpenseReport',
            fields=[
            ],
            options={
                'verbose_name': 'Employees',
                'verbose_name_plural': 'Employees',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('reports.employeemonthlyexpense',),
        ),
        migrations.CreateModel(
            name='IncomeForecastReport',
            fields=[
            ],
            options={
                'verbose_name': 'Income Forecast',
                'verbose_name_plural': 'Income Forecasts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('reports.incomeforecast',),
        ),
        migrations.CreateModel(
            name='InvoiceMonthlyExpenseReport',
            fields=[
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('reports.invoicemonthlyexpense',),
        ),
        migrations.CreateModel(
            name='MonthlyBudgetTrackerGraph',
            fields=[
            ],
            options={
                'verbose_name': 'Budget Graph',
                'verbose_name_plural': 'Budget Graph',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('reports.monthlybudgetgraph',),
        ),
        migrations.CreateModel(
            name='MonthlyBudgetTrackerReport',
            fields=[
            ],
            options={
                'verbose_name': 'Monthly Budget Tracker',
                'verbose_name_plural': 'Monthly Budget Trackers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('reports.monthlybudgettracker',),
        ),
        migrations.CreateModel(
            name='PipelineMonthlyExpenseReport',
            fields=[
            ],
            options={
                'verbose_name': 'Pipeline',
                'verbose_name_plural': 'Pipelines',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('reports.pipelinemonthlyexpense',),
        ),
        migrations.CreateModel(
            name='TypeTotalExpenseReport',
            fields=[
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('reports.typetotalexpense',),
        ),
    ]
