# Generated by Django 3.2.16 on 2023-03-10 10:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tools', '0020_alter_invoice_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorMonthlyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('expense', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.contractor')),
            ],
        ),
        migrations.CreateModel(
            name='ContractorMonthlyExpenseReport',
            fields=[
            ],
            options={
                'verbose_name': 'Contractors salary report',
                'verbose_name_plural': 'Contractors salary report',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('reports.contractormonthlyexpense',),
        ),
    ]
