# Generated by Django 3.2.16 on 2023-03-14 08:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0020_alter_invoice_client'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractormonthlyexpensereport',
            options={'verbose_name': 'Contractors', 'verbose_name_plural': 'Contractors'},
        ),
        migrations.CreateModel(
            name='EmployeeMonthlyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('expense', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeMonthlyExpenseReport',
            fields=[
            ],
            options={
                'verbose_name': 'Employees',
                'verbose_name_plural': 'Employees',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('reports.employeemonthlyexpense',),
        ),
    ]
