# Generated by Django 3.2.16 on 2023-03-31 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_auto_20230331_1619'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typetotalexpense',
            name='expense_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.expensetype'),
        ),
    ]
