# Generated by Django 3.2.16 on 2023-03-18 06:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0020_alter_invoice_client'),
        ('reports', '0002_auto_20230314_0805'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseMonthlyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('expense', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.expense')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseMonthlyExpenseReport',
            fields=[
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('reports.expensemonthlyexpense',),
        ),
    ]
