# Generated by Django 3.2.16 on 2023-09-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_invoicemonthlyexpense_invoicemonthlyexpensereport'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyBudgetGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyBudgetTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PipelineMonthlyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='IncomeForecastReport',
            fields=[
            ],
            options={
                'verbose_name': 'Income Forecast',
                'verbose_name_plural': 'Income Forecasts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('reports.incomeforecast',),
        ),
        migrations.CreateModel(
            name='MonthlyBudgetTrackerGraph',
            fields=[
            ],
            options={
                'verbose_name': 'Budget Graph',
                'verbose_name_plural': 'Budget Graph',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('reports.monthlybudgetgraph',),
        ),
        migrations.CreateModel(
            name='MonthlyBudgetTrackerReport',
            fields=[
            ],
            options={
                'verbose_name': 'Monthly Budget Tracker',
                'verbose_name_plural': 'Monthly Budget Trackers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('reports.monthlybudgettracker',),
        ),
        migrations.CreateModel(
            name='PipelineMonthlyExpenseReport',
            fields=[
            ],
            options={
                'verbose_name': 'Pipeline',
                'verbose_name_plural': 'Pipelines',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('reports.pipelinemonthlyexpense',),
        ),
    ]
