# Generated by Django 3.2.16 on 2023-03-23 05:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_expensemonthlyexpense_expensemonthlyexpensereport'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeTotalExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('Advertising', 'Advertising'), ('Bank Fees', 'Bank Fees'), ('Car', 'Car'), ('Cell Phone', 'Cell Phone'), ('Client Expense', 'Client Expense'), ('Computer', 'Computer'), ('Donation', 'Donation'), ('Insurance', 'Insurance'), ('Legal Fees', 'Legal Fees'), ('Office Expense', 'Office Expense'), ('Rent', 'Rent'), ('Recruitment & Training', 'Recruitment & Training'), ('Subscriptions', 'Subscriptions'), ('Tax Preparation Files', 'Tax Preparation Files'), ('Travel', 'Travel'), ('Utilities', 'Utilities'), ('Other', 'Other')], max_length=30)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('expense', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='expensemonthlyexpense',
            name='employee',
        ),
        migrations.DeleteModel(
            name='ExpenseMonthlyExpenseReport',
        ),
        migrations.DeleteModel(
            name='ExpenseMonthlyExpense',
        ),
        migrations.CreateModel(
            name='TypeTotalExpenseReport',
            fields=[
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('reports.typetotalexpense',),
        ),
    ]
