# Generated by Django 3.2.16 on 2023-03-29 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0022_auto_20230329_1456'),
        ('reports', '0004_auto_20230323_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typetotalexpense',
            name='expense_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.expensetype'),
        ),
    ]
