# Generated by Django 3.2.16 on 2023-10-11 15:01

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tools.client',),
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tools.pipeline',),
        ),
    ]
