# Generated by Django 3.2.16 on 2022-11-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientname', models.CharField(max_length=255)),
                ('address1', models.TextField()),
                ('address2', models.TextField()),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('zipcode', models.CharField(max_length=10)),
                ('clienttype', models.CharField(choices=[('AC', 'Active Client'), ('PC', 'Prospective Client')], max_length=2)),
                ('billingstructure', models.CharField(choices=[('R', 'Retainer'), ('PB', 'Project Based')], max_length=2)),
                ('billingtarget', models.TextField()),
                ('paymentterms', models.TextField()),
            ],
        ),
    ]
