# Generated by Django 3.2.16 on 2023-10-11 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('address1', models.TextField()),
                ('address2', models.TextField(blank=True, null=True)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('zipcode', models.CharField(max_length=10)),
                ('client_type', models.CharField(choices=[('AC', 'Active Client'), ('PC', 'Prospective Client')], max_length=2)),
                ('billing_structure', models.CharField(choices=[('R', 'Retainer'), ('PB', 'Project Based'), ('MX', 'Mixed')], max_length=2)),
                ('billing_target', models.TextField()),
                ('payment_terms', models.CharField(choices=[('N07', 'Net 7'), ('N15', 'Net 15'), ('N30', 'Net 30'), ('N45', 'Net 45'), ('OTR', 'Other')], max_length=50)),
                ('payment_terms_other', models.CharField(blank=True, help_text='Please enter number of days', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor_name', models.CharField(max_length=255)),
                ('contractor_role', models.CharField(max_length=20)),
                ('address1', models.TextField()),
                ('address2', models.TextField(blank=True, null=True)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('zipcode', models.CharField(max_length=10)),
                ('contractor_start_date', models.DateField()),
                ('contractor_hourly_salary', models.CharField(help_text='Please enter salary in USD', max_length=10)),
                ('contractor_expected_weekly_hours', models.CharField(max_length=5)),
                ('contractor_estimated_weekly_salary', models.CharField(help_text='in USD', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=255)),
                ('address1', models.TextField()),
                ('address2', models.TextField(blank=True, null=True)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('zipcode', models.CharField(max_length=10)),
                ('employee_start_date', models.DateField()),
                ('payment_structure', models.CharField(choices=[('W', 'Weekly'), ('BM', 'Bi-Monthly'), ('M', 'Monthly')], max_length=2)),
                ('employee_monthly_salary', models.CharField(help_text='Please enter salary in USD', max_length=10)),
                ('employee_monthly_tax', models.CharField(help_text='Please enter fee as %', max_length=10)),
                ('employee_net_income', models.CharField(max_length=10)),
                ('project_role', models.CharField(max_length=100, null=True)),
                ('fte_billable_rate', models.CharField(blank=True, max_length=10, null=True)),
                ('benefits', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_name', models.CharField(max_length=255)),
                ('expense_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('project_type', models.CharField(choices=[('A', 'Active'), ('P', 'Pipeline')], max_length=2)),
                ('billing_structure', models.CharField(choices=[('R', 'Retainer'), ('PB', 'Project Based')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.client')),
            ],
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_price', models.CharField(help_text='Please enter price in USD', max_length=10)),
                ('confidence', models.CharField(help_text='Please assign confidence as %', max_length=5)),
                ('no_of_payments', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=2)),
                ('expected_date_of_first_payment', models.DateField()),
                ('expected_date_of_second_payment', models.DateField(blank=True, null=True)),
                ('expected_date_of_third_payment', models.DateField(blank=True, null=True)),
                ('expected_date_of_forth_payment', models.DateField(blank=True, null=True)),
                ('expected_date_of_fifth_payment', models.DateField(blank=True, null=True)),
                ('expected_date_of_sixth_payment', models.DateField(blank=True, null=True)),
                ('expected_date_of_seventh_payment', models.DateField(blank=True, null=True)),
                ('expected_date_of_eighth_payment', models.DateField(blank=True, null=True)),
                ('expected_date_of_nineth_payment', models.DateField(blank=True, null=True)),
                ('expected_date_of_tenth_payment', models.DateField(blank=True, null=True)),
                ('expected_date_of_eleventh_payment', models.DateField(blank=True, null=True)),
                ('expected_date_of_twelfth_payment', models.DateField(blank=True, null=True)),
                ('total_value_in_forecast', models.CharField(help_text='Please enter price in USD', max_length=10)),
                ('estimated_payment_amount', models.CharField(help_text='Please enter amount in USD', max_length=10, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.client')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.project')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateField()),
                ('invoice_number', models.CharField(max_length=255)),
                ('invoice_status', models.CharField(choices=[('P', 'Paid'), ('S', 'Sent'), ('TBI', 'To Be Invoiced')], max_length=3)),
                ('expected_date_of_payment', models.DateField()),
                ('invoice_amount', models.CharField(help_text='Please enter amount in USD', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.client')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.project')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type_other', models.CharField(blank=True, max_length=255, null=True)),
                ('recurring_payment', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=2)),
                ('expense_payment_amount', models.CharField(help_text='Please enter amount in USD', max_length=10)),
                ('expense_frequency', models.CharField(blank=True, choices=[('W', 'Weekly'), ('BM', 'Bi-Monthly'), ('M', 'Monthly'), ('Q', 'Quarterly')], max_length=2, null=True)),
                ('date_of_first_payment', models.DateField(blank=True, null=True)),
                ('date_of_last_payment', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.expensetype')),
            ],
        ),
    ]
