# Generated by Django 3.2.16 on 2023-03-24 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('address1', models.TextField()),
                ('address2', models.TextField(blank=True, null=True)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('zipcode', models.CharField(max_length=10)),
                ('client_type', models.CharField(choices=[('AC', 'Active Client'), ('PC', 'Prospective Client')], max_length=2)),
                ('billing_structure', models.CharField(choices=[('R', 'Retainer'), ('PB', 'Project Based'), ('MX', 'Mixed')], max_length=2)),
                ('billing_target', models.TextField()),
                ('payment_terms', models.CharField(choices=[('N07', 'Net 7'), ('N15', 'Net 15'), ('N30', 'Net 30'), ('N45', 'Net 45'), ('OTR', 'Other')], max_length=50)),
                ('payment_terms_other', models.CharField(blank=True, help_text='Please enter number of days', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor_name', models.CharField(max_length=255)),
                ('address1', models.TextField()),
                ('address2', models.TextField(blank=True, null=True)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('zipcode', models.CharField(max_length=10)),
                ('contractor_start_date', models.DateField()),
                ('contractor_hourly_salary', models.CharField(help_text='Please enter salary as $USD', max_length=10)),
                ('contractor_expected_weekly_hours', models.CharField(max_length=5)),
                ('contractor_estimated_weekly_salary', models.CharField(help_text='as $USD', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=255)),
                ('address1', models.TextField()),
                ('address2', models.TextField(blank=True, null=True)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('zipcode', models.CharField(max_length=10)),
                ('employee_start_date', models.DateField()),
                ('payment_structure', models.CharField(choices=[('W', 'Weekly'), ('BM', 'Bi-Monthly'), ('M', 'Monthly')], max_length=2)),
                ('employee_monthly_salary', models.CharField(help_text='Please enter salary as $USD', max_length=10)),
                ('employee_monthly_tax', models.CharField(help_text='Please enter fee as %', max_length=10)),
                ('employee_net_income', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('Advertising', 'Advertising'), ('Bank Fees', 'Bank Fees'), ('Car', 'Car'), ('Cell Phone', 'Cell Phone'), ('Client Expense', 'Client Expense'), ('Computer', 'Computer'), ('Donation', 'Donation'), ('Insurance', 'Insurance'), ('Legal Fees', 'Legal Fees'), ('Office Expense', 'Office Expense'), ('Rent', 'Rent'), ('Recruitment & Training', 'Recruitment & Training'), ('Subscriptions', 'Subscriptions'), ('Tax Preparation Files', 'Tax Preparation Files'), ('Travel', 'Travel'), ('Utilities', 'Utilities'), ('Other', 'Other')], max_length=50)),
                ('expense_type_other', models.CharField(blank=True, max_length=255, null=True)),
                ('recurring_payment', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=2)),
                ('expense_payment_amount', models.CharField(help_text='Please enter amount as $USD', max_length=10)),
                ('expense_frequency', models.CharField(blank=True, choices=[('W', 'Weekly'), ('BM', 'Bi-Monthly'), ('M', 'Monthly'), ('Q', 'Quarterly')], max_length=2, null=True)),
                ('date_of_first_payment', models.DateField(blank=True, null=True)),
                ('date_of_last_payment', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('project_type', models.CharField(choices=[('A', 'Active'), ('P', 'Pipeline')], max_length=2)),
                ('confidence', models.CharField(help_text='Please assign confidence as %', max_length=5)),
                ('billing_structure', models.CharField(choices=[('R', 'Retainer'), ('PB', 'Project Based')], max_length=2)),
                ('total_fees', models.CharField(help_text='Please enter fee as $USD', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.client')),
            ],
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_price', models.CharField(help_text='Please enter price as $USD', max_length=10)),
                ('confidence', models.CharField(help_text='Please assign confidence as %', max_length=5)),
                ('no_of_payments', models.CharField(max_length=5)),
                ('total_value_in_forecast', models.CharField(help_text='Please enter price as $USD', max_length=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.client')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.project')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateField()),
                ('invoice_number', models.CharField(max_length=255)),
                ('invoice_status', models.CharField(choices=[('P', 'Paid'), ('S', 'Sent'), ('TBI', 'To Be Invoiced')], max_length=3)),
                ('expected_date_of_payment', models.DateField()),
                ('invoice_amount', models.CharField(help_text='Please enter amount as $USD', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.client')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.project')),
            ],
        ),
    ]
