# Generated by Django 3.2.16 on 2023-10-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='contractor_role',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
