# Generated by Django 3.2.16 on 2023-10-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_alter_contractor_contractor_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='confidence',
            field=models.CharField(choices=[('25', '25%'), ('50', '50%'), ('75', '75%'), ('100', '100%')], max_length=5),
        ),
    ]
