# Generated by Django 3.2.16 on 2023-04-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_auto_20230331_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='confidence',
            field=models.CharField(blank=True, help_text='Please assign confidence as %', max_length=5, null=True),
        ),
    ]
