# Generated by Django 3.2.16 on 2023-10-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_auto_20231017_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='status',
            field=models.CharField(choices=[('CUR', 'CUR'), ('WON', 'WON'), ('LOST', 'LOST')], default='CUR', max_length=4),
        ),
    ]
