# Generated by Django 3.2.16 on 2022-11-03 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_rename_clientname_client_client_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='billingstructure',
            new_name='billing_structure',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='billingtarget',
            new_name='billing_target',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='clienttype',
            new_name='client_type',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='paymentterms',
            new_name='payment_terms',
        ),
    ]
