# Generated by Django 3.2.16 on 2023-04-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_alter_project_confidence'),
    ]

    operations = [
        #migrations.AddField(
        #    model_name='pipeline',
        #    name='estimated_payment_amount',
        #    field=models.CharField(default=0,help_text='Please enter amount as $USD', max_length=10),
        #    preserve_default=False,
        #),
        migrations.AddField(
            model_name='pipeline',
            name='expected_date_of_first_payment',
            field=models.DateField(default='2023-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='no_of_payments',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=2),
        ),
    ]
