# Generated by Django 3.2.16 on 2022-11-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0006_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
