# Generated by Django 3.2.16 on 2022-11-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0007_alter_client_address2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=255)),
                ('address1', models.TextField()),
                ('address2', models.TextField(blank=True, null=True)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('zipcode', models.CharField(max_length=10)),
                ('employee_start_date', models.DateField()),
                ('payment_structure', models.CharField(choices=[('W', 'Weekly'), ('BM', 'Bi-Monthly'), ('M', 'Monthly')], max_length=2)),
                ('employee_monthly_salary', models.CharField(help_text='Please enter salary as $USD', max_length=10)),
                ('employee_monthly_tax', models.CharField(help_text='Please enter fee as %', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
