# Generated by Django 3.2.16 on 2022-12-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0010_contractor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('ADV', 'Advertising'), ('BNK', 'Bank Fees'), ('CAR', 'Car'), ('CEL', 'Cell Phone'), ('CLE', 'Client Expense'), ('COM', 'Computer'), ('DON', 'Donation'), ('INS', 'Insurance'), ('LEG', 'Legal Fees'), ('OFC', 'Office Expense'), ('RNT', 'Rent'), ('R&T', 'Recruitment & Training'), ('SUB', 'Subscriptions'), ('TAX', 'Tax Preparation Files'), ('TRV', 'Travel'), ('UTL', 'Utilities'), ('OTR', 'Other')], max_length=3)),
                ('expense_type_other', models.CharField(max_length=255)),
                ('recurring_payment', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=2)),
                ('expense_payment_amount', models.CharField(help_text='Please enter amount as $USD', max_length=10)),
                ('expense_frequency', models.CharField(choices=[('W', 'Weekly'), ('BM', 'Bi-Monthly'), ('M', 'Monthly'), ('Q', 'Quarterly')], max_length=2)),
                ('date_of_first_payment', models.DateField()),
                ('date_of_last_payment', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='contractor',
            name='contractor_estimated_weekly_salary',
            field=models.CharField(help_text='as $USD', max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='confidence',
            field=models.CharField(help_text='Please assign confidence as %', max_length=5),
        ),
        migrations.AlterField(
            model_name='project',
            name='total_fees',
            field=models.CharField(help_text='Please enter fee as $USD', max_length=10),
        ),
    ]
