# Generated by Django 3.2.16 on 2022-12-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0011_auto_20221208_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_type_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
