# Generated by Django 3.2.16 on 2022-12-08 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0012_alter_expense_expense_type_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('Advertising', 'Advertising'), ('Bank Fees', 'Bank Fees'), ('Car', 'Car'), ('Cell Phone', 'Cell Phone'), ('Client Expense', 'Client Expense'), ('Computer', 'Computer'), ('Donation', 'Donation'), ('Insurance', 'Insurance'), ('Legal Fees', 'Legal Fees'), ('Office Expense', 'Office Expense'), ('Rent', 'Rent'), ('Recruitment & Training', 'Recruitment & Training'), ('Subscriptions', 'Subscriptions'), ('Tax Preparation Files', 'Tax Preparation Files'), ('Travel', 'Travel'), ('Utilities', 'Utilities'), ('Other', 'Other')], max_length=50),
        ),
    ]
