# Generated by Django 3.2.16 on 2022-12-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0014_auto_20221208_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='payment_terms_other',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='billing_structure',
            field=models.CharField(choices=[('R', 'Retainer'), ('PB', 'Project Based'), ('MX', 'Mixed')], max_length=2),
        ),
        migrations.AlterField(
            model_name='client',
            name='payment_terms',
            field=models.CharField(choices=[('N07', 'Net 7'), ('N15', 'Net 15'), ('N30', 'Net 30'), ('N45', 'Net 45'), ('OTR', 'Other')], max_length=3),
        ),
    ]
