# Generated by Django 3.2.16 on 2022-12-08 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0015_auto_20221208_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='payment_terms_other',
            field=models.CharField(blank=True, help_text='Please enter number of days', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateField()),
                ('invoice_number', models.CharField(max_length=255)),
                ('invoice_status', models.CharField(choices=[('P', 'Paid'), ('S', 'Sent'), ('TBI', 'To Be Invoiced')], max_length=3)),
                ('expected_date_of_payment', models.DateField()),
                ('invoice_amount', models.CharField(help_text='Please enter amount as $USD', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.client')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.project')),
            ],
        ),
    ]
