# Generated by Django 3.2.16 on 2022-12-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0016_auto_20221208_0758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='client',
        ),
        migrations.AlterField(
            model_name='client',
            name='payment_terms',
            field=models.CharField(choices=[('N07', 'Net 7'), ('N15', 'Net 15'), ('N30', 'Net 30'), ('N45', 'Net 45'), ('OTR', 'Other')], max_length=50),
        ),
    ]
