# Generated by Django 3.2.16 on 2022-12-15 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0017_auto_20221215_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_price', models.CharField(help_text='Please enter price as $USD', max_length=10)),
                ('confidence', models.CharField(help_text='Please assign confidence as %', max_length=5)),
                ('no_of_payments', models.CharField(max_length=5)),
                ('total_value_in_forecast', models.CharField(help_text='Please enter price as $USD', max_length=10)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.project')),
            ],
        ),
    ]
