# Generated by Django 3.2.16 on 2022-12-29 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0018_pipeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tools.client'),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tools.client'),
            preserve_default=False,
        ),
    ]
