# Generated by Django 3.2.16 on 2023-03-23 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0020_alter_invoice_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='client',
        ),
        migrations.RemoveField(
            model_name='pipeline',
            name='client',
        ),
    ]
