# Generated by Django 3.2.16 on 2023-04-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0023_alter_project_confidence'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='pipeline',
            name='expected_date_of_first_payment',
            field=models.DateField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='no_of_payments',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=2),
        ),
    ]
