# Generated by Django 3.2.16 on 2023-04-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0024_auto_20230419_1011'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='project',
        #     name='confidence',
        # ),
        # migrations.RemoveField(
        #     model_name='project',
        #     name='total_fees',
        # ),
        # migrations.AddField(
        #     model_name='pipeline',
        #     name='estimated_payment_amount',
        #     field=models.CharField(default='', help_text='Please enter amount in USD', max_length=10),
        #     preserve_default=False,
        # ),
        migrations.AlterField(
            model_name='contractor',
            name='contractor_estimated_weekly_salary',
            field=models.CharField(help_text='in USD', max_length=10),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='contractor_hourly_salary',
            field=models.CharField(help_text='Please enter salary in USD', max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_monthly_salary',
            field=models.CharField(help_text='Please enter salary in USD', max_length=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_payment_amount',
            field=models.CharField(help_text='Please enter amount in USD', max_length=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_amount',
            field=models.CharField(help_text='Please enter amount in USD', max_length=10),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='estimated_price',
            field=models.CharField(help_text='Please enter price in USD', max_length=10),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='total_value_in_forecast',
            field=models.CharField(help_text='Please enter price in USD', max_length=10),
        ),
    ]
