# Generated by Django 3.2.16 on 2023-05-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0025_auto_20230425_1139'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='pipeline',
        #     name='estimated_payment_amount',
        #     field=models.CharField(help_text='Please enter amount in USD', max_length=10),
        #     preserve_default=False,
        # ),
        migrations.AddField(
            model_name='pipeline',
            name='expected_date_of_eighth_payment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='expected_date_of_eleventh_payment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='expected_date_of_fifth_payment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='expected_date_of_forth_payment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='expected_date_of_nineth_payment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='expected_date_of_second_payment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='expected_date_of_seventh_payment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='expected_date_of_sixth_payment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='expected_date_of_tenth_payment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='expected_date_of_third_payment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='expected_date_of_twelfth_payment',
            field=models.DateField(blank=True, null=True),
        ),
    ]
