# Generated by Django 3.2.16 on 2023-05-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0026_auto_20230506_1453'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='pipeline',
        #     name='estimated_payment_amount',
        #     field=models.CharField(default=1, help_text='Please enter amount in USD', max_length=10),
        #     preserve_default=False,
        # ),
    ]
